# Generated by Django 2.2.2 on 2019-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='template',
            field=models.CharField(blank=True, choices=[('default', 'Empty Note'), ('cornell', 'Cornell Style'), ('matrix', 'Matrix')], max_length=20, null=True),
        ),
    ]
