# Generated by Django 2.2.2 on 2019-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='template',
            field=models.CharField(choices=[('default', 'Empty Note'), ('cornell', 'Cornell Style'), ('matrix', 'Matrix')], default='default', max_length=20),
        ),
    ]
