# Generated by Django 2.2.2 on 2019-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190715_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, choices=[('calculus', 'Calculus'), ('algebra', 'Algebra'), ('statistics', 'Statistics'), ('economics', 'Economics'), ('astronomy', 'Astronomy'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('comp', 'Computer Science')], default='', max_length=20),
        ),
    ]
