# Generated by Django 2.2.2 on 2019-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190722_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
