# Generated by Django 2.2.2 on 2019-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='star',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
