# Generated by Django 2.2.2 on 2019-07-26 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20190726_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
